samples:
  - 2024-01-30-AACT75KM5

subdir: HGSVCpool1NEWp2
symlink_dir: ./HGSVCpool1NEWp2_symlinks  # Path to where symlinks will be created
bam_base_dir: /scratch/tweber/DATA/MC_DATA/STOCKS  # Base directory for the BAM files
predictions_dir: /g/korbel2/tsapalou/pools_2024/pool1new  # Base directory for the predictions
